# Generated by Django 3.0.4 on 2020-03-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=400)),
                ('directions', models.CharField(max_length=2000)),
                ('source', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
